// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iinmgjcvsyjkdhzthefw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpbm1namN2c3lqa2RoenRoZWZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTI4OTUsImV4cCI6MjA2NzcyODg5NX0.il-yT1QyXdBB7RyauuQrCGgtOtsftsBdpbnXiYBq35I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});